```dockerfile Dockerfile
ARG MESHAGENT_SDK_IMAGE="meshagent/python-sdk:latest" 

FROM ${MESHAGENT_SDK_IMAGE}

# Copy the deployable examples (starting with the simple chatbot)
COPY . /src

WORKDIR /src
```

